INSERT INTO GENRES (NAME) VALUES ('Комедия');
INSERT INTO GENRES (NAME) VALUES ('Драма');
INSERT INTO GENRES (NAME) VALUES ('Мультфильм');
INSERT INTO GENRES (NAME) VALUES ('Триллер');
INSERT INTO GENRES (NAME) VALUES ('Документальный');
INSERT INTO GENRES (NAME) VALUES ('Боевик');

INSERT INTO MPA_RATINGS (NAME) VALUES ('G');
INSERT INTO MPA_RATINGS (NAME) VALUES ('PG');
INSERT INTO MPA_RATINGS (NAME) VALUES ('PG-13');
INSERT INTO MPA_RATINGS (NAME) VALUES ('R');
INSERT INTO MPA_RATINGS (NAME) VALUES ('NC-17');